#!/usr/bin/env python3
"""
Generate team credentials for the NBR dashboard.

Idempotent: if teams_credentials.csv already exists, existing passwords are
preserved. Only new car entries get fresh passwords.

Outputs:
  <repo-root>/teams_credentials.csv  — distribute to teams, DO NOT commit
  dashboard/src/auth/auth-table.js   — SHA-256 lookup table, safe to commit

Usage:
  python3 tools/generate_team_credentials.py [--db /path/to/nbr_sector_times.db]
"""
import argparse
import csv
import hashlib
import random
import string
import sqlite3
import sys
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent
REPO_ROOT   = SCRIPT_DIR.parent

def find_db(hint=None) -> Path:
    if hint:
        p = Path(hint)
        if not p.exists():
            sys.exit(f"DB not found: {hint}")
        return p
    # Walk up from REPO_ROOT looking for nbr_sector_times.db
    candidate = REPO_ROOT
    for _ in range(5):
        p = candidate / "nbr_sector_times.db"
        if p.exists():
            return p
        candidate = candidate.parent
    sys.exit(
        "Could not find nbr_sector_times.db. "
        "Pass --db /path/to/nbr_sector_times.db explicitly."
    )

CSV_OUT       = REPO_ROOT / "teams_credentials.csv"
AUTH_TABLE_JS = REPO_ROOT / "dashboard/src/auth/auth-table.js"

# ── Helpers ────────────────────────────────────────────────────────────────────
_RNG = random.SystemRandom()
_CHARS = string.ascii_letters + string.digits

def make_password(length: int = 8) -> str:
    return "".join(_RNG.choice(_CHARS) for _ in range(length))

def sha256_key(login: str, password: str) -> str:
    return hashlib.sha256(f"{login}:{password}".encode()).hexdigest()

def car_slug(car_no: int) -> str:
    return f"car-{car_no:03d}"

# ── Load existing credentials (idempotency) ────────────────────────────────────
def load_existing() -> dict:
    """Returns {login: password} from CSV if it already exists."""
    if not CSV_OUT.exists():
        return {}
    with open(CSV_OUT, newline="", encoding="utf-8") as f:
        return {row["login"]: row["password"] for row in csv.DictReader(f)}

# ── DB ─────────────────────────────────────────────────────────────────────────
def get_cars(db: Path) -> list:
    conn = sqlite3.connect(db)
    rows = conn.execute(
        "SELECT car_no, drivers, class FROM cars ORDER BY class, car_no"
    ).fetchall()
    conn.close()
    return rows

# ── Main ────────────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", metavar="PATH", help="Path to nbr_sector_times.db")
    args = parser.parse_args()

    db = find_db(args.db)
    print(f"Using DB: {db}")

    existing = load_existing()
    cars     = get_cars(db)

    rows = []
    new_count = 0
    for car_no, drivers, cls in cars:
        login   = car_slug(car_no)
        display = f"Car #{car_no} · {drivers}"
        if login in existing:
            password = existing[login]
        else:
            password  = make_password()
            new_count += 1
        rows.append({"team": display, "class": cls, "login": login, "password": password})

    # ── Write CSV ─────────────────────────────────────────────────────────────
    with open(CSV_OUT, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["team", "class", "login", "password"])
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {len(rows)} entries to {CSV_OUT} ({new_count} new)")

    # ── Write auth-table.js ───────────────────────────────────────────────────
    entries = []
    for row in rows:
        key  = sha256_key(row["login"], row["password"])
        name = row["team"].replace('"', "'")
        entries.append(f'  "{key}": "{name}"')

    AUTH_TABLE_JS.parent.mkdir(parents=True, exist_ok=True)
    AUTH_TABLE_JS.write_text(
        "// Auto-generated by tools/generate_team_credentials.py — DO NOT EDIT BY HAND\n"
        "// REPLACE: Google Apps Script Web App URL\n"
        'export const WEBHOOK_URL = "";\n'
        "\n"
        "export const AUTH_TABLE = {\n"
        + ",\n".join(entries) + "\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"Wrote auth table ({len(rows)} entries) to {AUTH_TABLE_JS}")

if __name__ == "__main__":
    main()
